# -*- coding: utf-8 -*-
"""Жуков, Акимцев, Колегов.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxuUJRMSzbJ80LoZpB4kcTU9eA6-viZi
"""

!pip install transformers

from transformers import pipeline
classifier = pipeline("sentiment-analysis",
 "blanchefort/rubert-base-cased-sentiment")
classifier("Я обожаю инженерию машинного обучения!")

!pip install sentencepiece

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-ru-en")

model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-ru-en")

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-ru-en")
translator("Привет")